### PR TITLE
Making the SharingService CosmosDbCache a persisted DB cache

### PR DESCRIPTION
**Pull request by reneschulte**
The SharingService CosmosDbCache is now an actual persisted DB cache which is not recreated each time the app service is restarted and also uses the actual last row number if a new entry is going to be inserted.

### CODE REVIEW

**Comment by tisaud** [comment]
@reneschulte Hello! i find some questions when I learn this academy .i can find anchors When the app is running properly(Android/SharingService).but two or three days later,i cannot find anchors (feedback no anchor number /Data of cosmos db lost). Can you give me a hint of what caused the problem

**Comment by reneschulte** [comment]
@tisaud This PR addresses the problem you are facing. The sample code without my PR would recreate a new Table each time the app service is restarted which can happen whenever Azure decides to move the resources. Merge my PR into your source code and you should be good to go. 
Though note there's another piece in the sample code where it sets the expiration date of the anchor to 7 days or 48h, so you might wanna fix that.

**Comment by tisaud** [comment]
@reneschulte Thanks!

**Comment by Alberto-Vega-MSFT** [comment]
@reneschulte Thanks for your contribution!

**Comment by reneschulte** [comment]
Sure thing! Happy to help and glad it was useful. 🙌

**Pull request merged**
